edit_uri: ''
extra_css:
- assets/css/style.css
- assets/css/custom.css
- assets/css/extra.css
extra_javascript:
- defer: true
  path: https://unpkg.com/vis-network/standalone/umd/vis-network.min.js
- defer: true
  path: https://cdn.jsdelivr.net/npm/marked/marked.min.js
- defer: true
  path: assets/js/script.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
nav:

repo_name: Resck/Takwara-Tech
repo_url: https://github.com/Resck/Takwara-Tech
site_name: Tecnologia Takwara
theme:
  custom_dir: overrides
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.instant: true
  - navigation.expand
  - content.code.annotate
  - search.suggest
  - search.highlight
  - navigation.sticky
  language: pt-BR
  logo: assets/images/logo.png
  name: material
  palette:
  - accent: indigo
    primary: green
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Mudar para o modo claro
  - accent: indigo
    primary: green
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Mudar para o modo escuro
