# ---------------- Início do arquivo mkdocs.yml ----------------

site_name: Tecnologia Takwara

theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'amber'

nav:
  - 'Início': 'index.md'
  - 'Chatbot': 'chatbot.md'

  - 'Artigos':
      - 'Forno Ecológico': 'Artigos/Forno Ecológico.md'
  - 'Patentes e Memoriais':
      - 'Roteiro para Ensaios': 'PATENTES/6- Roteiro para Ensaios.md'
      - 'Conexões Geodésicas': 'PATENTES/7 - Memorial Conexões Geodésicos.md'

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: "2-6"

extra_css:
  - assets/css/style.css

# CORREÇÃO AQUI: Liste todos os scripts em uma única entrada de extra_javascript
extra_javascript:
  - assets/js/script.js        # O script do chatbot
  - assets/js/calculadora.js   # O novo script da calculadora

# ---------------- Fim do arquivo mkdocs.yml ----------------