edit_uri: ''
extra_css:
- assets/css/style.css
- assets/css/custom.css
extra_javascript:
- defer: true
  path: https://unpkg.com/vis-network/standalone/umd/vis-network.min.js
- defer: true
  path: https://cdn.jsdelivr.net/npm/marked/marked.min.js
- defer: true
  path: assets/js/script.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
nav:
- Tecnologias:
    children:
    - Forno Ecológico.md: A1. [icon:fas fa-tools] Tecnologias /a1.2 Forno Ecológico.md
    - Sistema de Reforço.md: A1. [icon:fas fa-tools] Tecnologias /a1.3 Sistema de
        Reforço.md
    - Conexões Geodésicos.md: A1. [icon:fas fa-tools] Tecnologias /a1.4 Conexões Geodésicos.md
    - PU + Bambu.md: A1. [icon:fas fa-tools] Tecnologias /a1.5 PU + Bambu.md
    - Painéis de Bambu.md: A1. [icon:fas fa-tools] Tecnologias /a1.6 Painéis de Bambu.md
    - Tijolos e Briquetes.md: A1. [icon:fas fa-tools] Tecnologias /a1.7 Tijolos e
        Briquetes.md
    - Roteiro para Ensaios.md: A1. [icon:fas fa-tools] Tecnologias /a1.8 Roteiro para
        Ensaios.md
    - Forno Ecológico.md: A1. [icon:fas fa-tools] Tecnologias /a1.9 Forno Ecológico.md
    icon: fas fa-tools
- O Bambu:
    children:
    - Visão Geral.md: A2. [icon:fas fa-seedling] O Bambu/a2.1 Visão Geral.md
    - 'Brasil: A cadeia Digital.md': 'A2. [icon:fas fa-seedling] O Bambu/a2.2 Brasil:
        A cadeia Digital.md'
    - Caracterização Física.md: A2. [icon:fas fa-seedling] O Bambu/a2.2 Caracterização
        Física.md
    - O Ecossistema do Bambu no Brasil.md: A2. [icon:fas fa-seedling] O Bambu/a2.3
        O Ecossistema do Bambu no Brasil.md
    - Mercado Global.md: A2. [icon:fas fa-seedling] O Bambu/a2.4 Mercado Global.md
    - O Bambu na Ásia.md: A2. [icon:fas fa-seedling] O Bambu/a2.5 O Bambu na Ásia.md
    - O Broto de Bambu.md: A2. [icon:fas fa-seedling] O Bambu/a2.6 O Broto de Bambu.md
    - O carvão e o Pirolenhoso.md: A2. [icon:fas fa-seedling] O Bambu/a2.7 O carvão
        e o Pirolenhoso.md
    icon: fas fa-seedling
- Personalidades:
    children:
    - Jayme Gonçalves.md: A2.a [icon:fas fa-users] Personalidades/a2.a1 Jayme Gonçalves.md
    - Khorow Ghavami.md: A2.a [icon:fas fa-users] Personalidades/a2.a2 Khorow Ghavami.md
    - Ludovico Beraldo e Reis Pereira.md: A2.a [icon:fas fa-users] Personalidades/a2.a3
        Ludovico Beraldo e Reis Pereira.md
    - Oscar Hidalgo.md: A2.a [icon:fas fa-users] Personalidades/a2.a4 Oscar Hidalgo.md
    - Simon Velez.md: A2.a [icon:fas fa-users] Personalidades/a2.a5 Simon Velez.md
    icon: fas fa-users
- Domos [icon:fas fa-atom] Geodésicos:
  - Dados Estruturais.md: A3. Domos [icon:fas fa-atom] Geodésicos/a3.1 Dados Estruturais.md
  - Especificações Tecnicas.md: A3. Domos [icon:fas fa-atom] Geodésicos/a3.2 Especificações
      Tecnicas.md
  - Ferramentas para Layout.md: A3. Domos [icon:fas fa-atom] Geodésicos/a3.3 Ferramentas
      para Layout.md
- O PU Vegetal:
    children:
    - A Imperveg Polímeros Vegetais.md: A4. [icon:fas fa-flask] O PU Vegetal/a4.1
        A Imperveg Polímeros Vegetais.md
    - Orgânicos X Sintéticos .md: A4. [icon:fas fa-flask] O PU Vegetal/a4.2 Orgânicos
        X Sintéticos .md
    icon: fas fa-flask
- Críticas Paradoxais:
    children:
    - Brasil Paradoxo da Sustentabilidade.md: A6. [icon:fas fa-file-alt] Críticas
        Paradoxais/a5.1 Brasil Paradoxo da Sustentabilidade.md
    - Deficit Habitacional.md: A6. [icon:fas fa-file-alt] Críticas Paradoxais/a5.2
        Deficit Habitacional.md
    - Resposta a Crise Habitacional.md: A6. [icon:fas fa-file-alt] Críticas Paradoxais/a5.3
        Resposta a Crise Habitacional.md
    - A Maloca de Concreto.md: A6. [icon:fas fa-file-alt] Críticas Paradoxais/a6.4
        A Maloca de Concreto.md
    icon: fas fa-file-alt
- Contribuir:
    children:
    - Colaboração.md: A7. [icon:fas fa-file-alt] Contribuir/a6.2 Colaboração.md
    - O Github.md: A7. [icon:fas fa-file-alt] Contribuir/a6.3 O Github.md
    icon: fas fa-file-alt
- ? ''
  : grafo.md
- ? ''
  : index.md
repo_name: Resck/Takwara-Tech
repo_url: https://github.com/Resck/Takwara-Tech
site_name: Tecnologia Takwara
theme:
  custom_dir: overrides
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.instant: false
  - navigation.expand
  - content.code.annotate
  - search.suggest
  - search.highlight
  - navigation.sticky
  language: pt-BR
  logo: assets/images/logo.png
  name: material
  palette:
  - accent: indigo
    primary: green
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Mudar para o modo claro
  - accent: indigo
    primary: green
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Mudar para o modo escuro
