edit_uri: ''
extra_css:
- assets/css/style.css
- assets/css/custom.css
extra_javascript:
- assets/js/script.js
- assets/js/calculadora.js
- https://unpkg.com/vis-network/standalone/umd/vis-network.min.js
- assets/js/graph.js
- assets/js/modal.js
- assets/js/toolbox.js
- https://cdn.jsdelivr.net/npm/marked/marked.min.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
- toc:
    permalink: true
nav:
  - Tecnologia Takwara:
    - Ecopo do Projeto.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.1 Ecopo
        do Projeto.md
    - Forno Ecológico.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.2 Forno
        Ecológico.md
    - Sistema de Reforço.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.3
        Sistema de Reforço.md
    - Conexões Geodésicos.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.4
        Conexões Geodésicos.md
    - PU + Bambu.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.5 PU + Bambu.md
    - Painéis de Bambu.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.6 Painéis
        de Bambu.md
    - Tijolos e Briquetes.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.7
        Tijolos e Briquetes.md
    - Roteiro para Ensaios.md: A1. A Tecnologia Takwara/A1. Tecnologia Takwara/a1.8
        Roteiro para Ensaios.md
- O Bambu:
  - Personalidades:
    - Jayme Gonçalves.md: A2. O Bambu/A2.a Personalidades/a2.a1 Jayme Gonçalves.md
    - Khorow Ghavami.md: A2. O Bambu/A2.a Personalidades/a2.a2 Khorow Ghavami.md
    - Ludovico Beraldo e Reis Pereira.md: A2. O Bambu/A2.a Personalidades/a2.a3 Ludovico
        Beraldo e Reis Pereira.md
    - Oscar Hidalgo.md: A2. O Bambu/A2.a Personalidades/a2.a4 Oscar Hidalgo.md
    - Simon Velez.md: A2. O Bambu/A2.a Personalidades/a2.a5 Simon Velez.md
  - Visão Geral.md: A2. O Bambu/a2.1 Visão Geral.md
  - 'Brasil: A cadeia Digital.md': 'A2. O Bambu/a2.2 Brasil: A cadeia Digital.md'
  - Caracterização Física.md: A2. O Bambu/a2.2 Caracterização Física.md
  - O Ecossistema do Bambu no Brasil.md: A2. O Bambu/a2.3 O Ecossistema do Bambu no
      Brasil.md
  - Mercado Global.md: A2. O Bambu/a2.4 Mercado Global.md
  - O Bambu na Ásia.md: A2. O Bambu/a2.5 O Bambu na Ásia.md
  - O Broto de Bambu.md: A2. O Bambu/a2.6 O Broto de Bambu.md
  - O carvão e o Pirolenhoso.md: A2. O Bambu/a2.7 O carvão e o Pirolenhoso.md
- Domos Geodésicos:
  - Dados Estruturais.md: A3. Domos Geodésicos/a3.1 Dados Estruturais.md
  - Especificações Tecnicas.md: A3. Domos Geodésicos/a3.2 Especificações Tecnicas.md
  - Ferramentas para Layout.md: A3. Domos Geodésicos/a3.3 Ferramentas para Layout.md
- O PU Vegetal:
  - A Imperveg Polímeros Vegetais.md: A4. O PU Vegetal/a4.1 A Imperveg Polímeros Vegetais.md
  - Orgânicos X Sintéticos .md: A4. O PU Vegetal/a4.2 Orgânicos X Sintéticos .md
- Artigos:
  - Brasil Paradoxo da Sustentabilidade.md: A5. Artigos/a5.1 Brasil Paradoxo da Sustentabilidade.md
  - Deficit Habitacional.md: A5. Artigos/a5.2 Deficit Habitacional.md
  - Resposta a Crise Habitacional.md: A5. Artigos/a5.3 Resposta a Crise Habitacional.md
- Sobre Este Repositório:
  - Código de Conduta.md: A6. Sobre Este Repositório/a6.2 Código de Conduta.md
  - O Github.md: A6. Sobre Este Repositório/a6.3 O Github.md
repo_name: Resck/Takwara-Tech
repo_url: https://github.com/Resck/Takwara-Tech
site_name: Tecnologia Takwara
theme:
  custom_dir: overrides
  favicon: /assets/images/favicon.png
  features:
  - navigation.expand
  - content.code.annotate
  - search.suggest
  - search.highlight
  - navigation.sticky
  language: pt-BR
  logo: /assets/images/logo.png
  name: material
  palette:
  - accent: indigo
    primary: green
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Mudar para o modo claro
  - accent: indigo
    primary: green
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Mudar para o modo escuro
