site_name: Tecnologia Takwara
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'amber'

# Define a navegação do site com os caminhos corretos
nav:
  - 'Início': 'index.md'
  - 'Artigos':
    - 'Forno Ecológico': 'Artigos/Forno Ecológico.md'
    - 'HIS e Briquetes': 'Artigos/HIS e BRIQUETES STL.md'
    - 'Normas para Ensaios': 'Artigos/Normas para ensaios.md'
  - 'Patentes e Memoriais':
    - 'Roteiro para Ensaios': 'PATENTES/6- Roteiro para Ensaios.md'
    - 'Conexões Geodésicas': 'PATENTES/7 - Memorial Conexões Geodésicos.md'
    - 'Memorial Forno Ecológico': 'PATENTES/8 - Memorial Forno Ecológico.md'
    - 'Painéis de Bambu': 'PATENTES/Painéis de Bambu - Takwara Tech.md'
    # Adicione os outros arquivos que desejar da mesma forma...

# Inclui os nossos arquivos de CSS e JavaScript personalizados
extra_css:
  - assets/css/style.css
extra_javascript:
  - assets/js/script.js