edit_uri: ''
extra_css:
- assets/css/style.css
- assets/css/custom.css
extra_javascript:
- defer: true
  path: https://unpkg.com/vis-network/standalone/umd/vis-network.min.js
- defer: true
  path: https://cdn.jsdelivr.net/npm/marked/marked.min.js
- defer: true
  path: assets/js/script.js
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
nav:
- Tecnologias:
  - Forno Ecológico.md: A1. Tecnologias /a1.2 Forno Ecológico
  - Sistema de Reforço.md: A1. Tecnologias /a1.3 Sistema de Reforço
  - Conexões Geodésicos.md: A1. Tecnologias /a1.4 Conexões Geodésicos
  - PU + Bambu.md: A1. Tecnologias /a1.5 PU + Bambu
  - Painéis de Bambu.md: A1. Tecnologias /a1.6 Painéis de Bambu
  - Tijolos e Briquetes.md: A1. Tecnologias /a1.7 Tijolos e Briquetes
  - Roteiro para Ensaios.md: A1. Tecnologias /a1.8 Roteiro para Ensaios
  - Forno Ecológico.md: A1. Tecnologias /a1.9 Forno Ecológico
- O Bambu:
  - Visão Geral.md: A2.  O Bambu/a2.1 Visão Geral
  - 'Brasil: A cadeia Digital.md': 'A2.  O Bambu/a2.2 Brasil: A cadeia Digital'
  - Caracterização Física.md: A2.  O Bambu/a2.2 Caracterização Física
  - O Ecossistema do Bambu no Brasil.md: A2.  O Bambu/a2.3 O Ecossistema do Bambu
      no Brasil
  - Mercado Global.md: A2.  O Bambu/a2.4 Mercado Global
  - O Bambu na Ásia.md: A2.  O Bambu/a2.5 O Bambu na Ásia
  - O Broto de Bambu.md: A2.  O Bambu/a2.6 O Broto de Bambu
  - O carvão e o Pirolenhoso.md: A2.  O Bambu/a2.7 O carvão e o Pirolenhoso
  - Carvão de Bambu = 0 => CO2.md: A2.  O Bambu/a5.4 Carvão de Bambu = 0 => CO2
- Personalidades:
  - Jayme Gonçalves.md: A2.a Personalidades/a2.a1 Jayme Gonçalves
  - Khorow Ghavami.md: A2.a Personalidades/a2.a2 Khorow Ghavami
  - Ludovico Beraldo e Reis Pereira.md: A2.a Personalidades/a2.a3 Ludovico Beraldo
      e Reis Pereira
  - Oscar Hidalgo.md: A2.a Personalidades/a2.a4 Oscar Hidalgo
  - Simon Velez.md: A2.a Personalidades/a2.a5 Simon Velez
- O PU Vegetal:
  - A Imperveg Polímeros Vegetais.md: A3. O PU Vegetal/a4.1 A Imperveg Polímeros Vegetais
  - Orgânicos X Sintéticos .md: A3. O PU Vegetal/a4.2 Orgânicos X Sintéticos
- Domos Geodésicos:
  - Dados Estruturais.md: A4. Domos Geodésicos/a3.1 Dados Estruturais
  - Especificações Tecnicas.md: A4. Domos Geodésicos/a3.2 Especificações Tecnicas
  - Ferramentas para Layout.md: A4. Domos Geodésicos/a3.3 Ferramentas para Layout
- COP30:
  - O Paradoxo da Sustentabilidade.md: A6. COP30/a5.1 O Paradoxo da Sustentabilidade
  - Deficit Habitacional.md: A6. COP30/a5.2 Deficit Habitacional
  - O Paradoxo do Bambu.md: A6. COP30/a6.1 O Paradoxo do Bambu
  - A Arquitetura das Influências.md: A6. COP30/a6.2 A Arquitetura das Influências
  - A Maloca de Concreto.md: A6. COP30/a6.4 A Maloca de Concreto
- Como  Contribuir:
  - Colaboração.md: A7. Como  Contribuir/a6.2 Colaboração
  - O Github.md: A7. Como  Contribuir/a6.3 O Github
- grafo: grafo
- index: index
repo_name: Resck/Takwara-Tech
repo_url: https://github.com/Resck/Takwara-Tech
site_name: Tecnologia Takwara
theme:
  custom_dir: overrides
  favicon: assets/images/favicon.png
  features:
  - navigation.tabs
  - navigation.instant: true
  - navigation.expand
  - content.code.annotate
  - search.suggest
  - search.highlight
  - navigation.sticky
  language: pt-BR
  logo: assets/images/logo.png
  name: material
  palette:
  - accent: indigo
    primary: green
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Mudar para o modo claro
  - accent: indigo
    primary: green
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Mudar para o modo escuro
